---
kind: pipeline
type: docker
name: Deploy to bbaovanc.com

trigger:
    branch:
        - master
    event:
        exclude:
            - pull_request

steps:
    - name: submodules
      image: alpine/git
      commands:
          - git submodule update --init --recursive

    - name: build
      image: klakegg/hugo:ext-ubuntu-ci # og:video doesn't work on the alpine one for some reason
      commands:
          - hugo

    - name: compress
      image: bbaovanc/compression:latest
      commands:
          - time ./compress.sh

    - name: upload
      image: appleboy/drone-scp
      settings:
          host: bbaovanc.com
          port: 2222
          username: droneci
          key:
              from_secret: SSH_KEY
          target: /var/www/bbaovanc/public/
          rm: true
          source: public/
          strip_components: 1
