baseURL = "https://bbaovanc.com"
theme = "bobatheme"
languageCode = "en-US"
author = "bbaovanc"
title = "bbaovanc's Website"
sectionPagesMenu = "main"
enableRobotsTXT = true

[params]
  # these are for the OpenGraph/Twitter embeds in Hugo
  description = "My personal website"
  title = "bbaovanc.com"

  # these are for favicons in bobatheme
  faviconICO = "/favicon.ico"
  faviconPNG = "/favicon.png"

  # breadcrumb navigation
  breadcrumbnav = false
