baseURL = "https://bbaovanc.com"
theme = "bobatheme"
defaultContentLanguage = "en"
copyright = 'This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.'
sectionPagesMenu = "main"
enableRobotsTXT = true
paginate = 5
enableGitInfo = true

[author]
  name = "BBaoVanC"
  email = "bbaovanc@bbaovanc.com"

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true

[params]
  # these are for the OpenGraph/Twitter embeds in Hugo
  description = "My personal website"

  # these are for favicons in bobatheme
  faviconICO = "/favicon.ico"
  faviconPNG = "/favicon.png"

  # show word count and/or reading time
  wordcount = true
  readingtime = true

  # used for last update
  repoURL = "https://github.com/BBaoVanC/bbaovanc.com"

[languages]
  [languages.en]
    languageName = "English"
    title = "bbaovanc's Website"
    weight = 1

  [languages.es]
    languageName = "Español"
    title = "sitio web de bbaovanc"
    weight = 2
    [languages.es.params]
      description = "Mi sitio web personal"
