baseURL: https://bbaovanc.com
theme: bobatheme
defaultContentLanguage: en
copyright: '&copy; 2021 bbaovanc <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>'
sectionPagesMenu: main
enableRobotsTXT: true
paginate: 10
enableGitInfo: true

taxonomies:
  _merge: deep

author:
  name: bbaovanc

markup: # this just keeps the bobatheme markup styling
  _merge: deep

related:
  includeNewer: true # this is the only non-default settings
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 80
    - name: date
      weight: 10
  threshold: 80
  toLower: false

params:
  # these are for the OpenGraph/Twitter embeds in Hugo
  description: My personal website

  # these are for favicons in bobatheme (unset by default)
  faviconICO: favicon.ico
  faviconPNG: favicon.png

  # show reading time (enabled by default)
  readingtime: true

  # used for "View source" (unset by default)
  gitFileURL: https://github.com/BBaoVanC/bbaovanc.com/blob/master
  gitFileIcon: code

  talkyardServerUrl: "https://talkyard.bbaovanc.com"
  talkyardScriptUrl: "https://talkyard.bbaovanc.com/-/talkyard-comments.min.js"

  footer: true

# see https://gohugo.io/about/hugo-and-gdpr/#all-privacy-settings
# you probably want to keep this default
privacy:
  _merge: deep

languages:
  en:
    languageName: English
    title: bbaovanc's Website
    weight: 1
    menu:
      main:
        - identifier: forum
          name: Forum
          url: https://talkyard.bbaovanc.com

  es:
    languageName: Español
    title: sitio web de bbaovanc
    weight: 2
    params:
      description: Mi sitio web personal
    menu:
      main:
        - identifier: foro
          name: Foro
          url: https://talkyard.bbaovanc.com
