baseURL: https://bbaovanc.com
theme: bobatheme
defaultContentLanguage: en
copyright: '&copy; 2021 bbaovanc <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>'
sectionPagesMenu: main
enableRobotsTXT: true
paginate: 10
enableGitInfo: true

taxonomies:
  _merge: deep

author:
  name: bbaovanc

markup: # this just keeps the bobatheme markup styling
  _merge: deep

related:
  includeNewer: true
  indices:
    #- name: keywords
    #  weight: 100
    - name: tags
      weight: 80
    - name: date
      weight: 10
  threshold: 80
  toLower: true

params:
  # these are for the OpenGraph/Twitter embeds in Hugo
  description: My personal website

  # these are for favicons in bobatheme (unset by default)
  faviconICO: favicon.ico
  faviconPNG: favicon.png

  # show reading time (enabled by default)
  readingtime: true

  # used for "View source" (unset by default)
  gitFileURL: https://github.com/BBaoVanC/bbaovanc.com/blob/master
  gitFileIcon: code

  # display a "Latest Posts" section on the homepage below its content
  homepageLatestPosts: true

  footer: >-
    See the [anonymous and privacy-friendly
    analytics](https://plausible.bbaovanc.com/bbaovanc.com) for this site,
    powered by [Plausible](https://plausible.io).

# see https://gohugo.io/about/hugo-and-gdpr/#all-privacy-settings
# you probably want to keep this default
privacy:
  _merge: deep

languages:
  en:
    languageName: English
    title: bbaovanc's Website
    weight: 1
    menu:
      main:
        - identifier: forum
          name: Forum
          url: https://forum.bbaovanc.com
