baseURL = "https://bbaovanc.com"
theme = "bobatheme"
defaultContentLanguage = "en"
author = "bbaovanc"
sectionPagesMenu = "main"
enableRobotsTXT = true
paginate = 5
enableGitInfo = true

[params]
  # these are for the OpenGraph/Twitter embeds in Hugo
  description = "My personal website"

  # these are for favicons in bobatheme
  faviconICO = "/favicon.ico"
  faviconPNG = "/favicon.png"

  # show word count and/or reading time
  wordcount = true
  readingtime = true

  # used for last update
  repoURL = "https://github.com/BBaoVanC/bbaovanc.com"

[languages]
  [languages.en]
    languageName = "English"
    title = "bbaovanc's Website"
    weight = 1

  [languages.es]
    languageName = "Español"
    title = "sitio web de bbaovanc"
    weight = 2
    [languages.es.params]
      description = "Mi sitio web personal"
