baseURL = "https://bbaovanc.com"
theme = "bobatheme"
languageCode = "en-US"
author = "bbaovanc"
title = "bbaovanc's Website"
sectionPagesMenu = "main"
enableRobotsTXT = true

# these are for the OpenGraph/Twitter embeds
[params]
  description = "My personal website"
  title = "bbaovanc.com"
