name: Audit

on:
  push:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Read HUGO_VERSION
        id: hugo_version
        run: echo "HUGO_VERSION=$(cat HUGO_VERSION)" >> $GITHUB_OUTPUT

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ steps.hugo_version.outputs.HUGO_VERSION }}
          extended: true

      - name: Build
        run: |
          AUDIT=y ./build.sh

      # For the following steps, see
      # https://discourse.gohugo.io/t/audit-your-published-site-for-problems/35184

      # https://gohugo.io/troubleshooting/audit/
      - name: Search for audit strings
        run: |
          ! grep -inorE "<\!-- raw HTML omitted -->|ZgotmplZ|\[i18n\]|\(<nil>\)|(&lt;nil&gt;)|hahahugo" public/

      # see layouts/baseof.html in bobatheme
      - name: Audit - YUZSIQGHE (non-overridden "main" block)
        if: always()
        run: |
          ! grep -inorE "YUZSIQGHE" public/
