name: Deploy

concurrency:
  group: deploy-production
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: bbaovanc.com
      url: https://bbaovanc.com
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Read HUGO_VERSION
        id: hugo_version
        run: echo "HUGO_VERSION=$(cat HUGO_VERSION)" >> $GITHUB_OUTPUT
      - name: Read PAGEFIND_VERSION
        id: pagefind_version
        # put this one in the env so it's easier to call in the shell
        run: echo "PAGEFIND_VERSION=$(cat PAGEFIND_VERSION)" >> $GITHUB_ENV

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ steps.hugo_version.outputs.HUGO_VERSION }}
          extended: true

      - name: Download Pagefind
        run: |
          mkdir -p ~/.local/bin/
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          curl -L "https://github.com/Pagefind/pagefind/releases/download/$PAGEFIND_VERSION/pagefind-$PAGEFIND_VERSION-x86_64-unknown-linux-musl.tar.gz" |
            tar zxv -C ~/.local/bin pagefind

      - name: Build
        run: ./build.sh

      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
          ssh-host: srv.bbaovanc.com
          ssh-port: 2222

      - name: Upload
        uses: up9cloud/action-rsync@v1
        env:
          HOST: srv.bbaovanc.com
          USER: droneci
          PORT: 2222
          SOURCE: public/
          MODE: push
          VERBOSE: true
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /var/www/bbaovanc.com/public/
          ARGS: -avPzc --delete-delay --exclude=/.git/ --exclude=/.github/
