name: Diff

on:
  push:
  pull_request:

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout previous (pull_request)
        if: github.event.pull_request
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Checkout previous (push)
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ github.event.before }}

      - name: Read HUGO_VERSION (previous)
        id: hugo_version_old
        run: echo "HUGO_VERSION=$(cat HUGO_VERSION)" >> $GITHUB_OUTPUT

      - name: Setup Hugo (previous)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ steps.hugo_version_old.outputs.HUGO_VERSION }}
          extended: true

      - name: Build previous
        run: |
          NO_SEARCH=y NO_COMPRESS=y DEST=old/ ./build.sh

      - name: Checkout current
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          clean: false

      - name: Read HUGO_VERSION (current)
        id: hugo_version_new
        run: echo "HUGO_VERSION=$(cat HUGO_VERSION)" >> $GITHUB_OUTPUT

      - name: Setup Hugo (current)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ steps.hugo_version_new.outputs.HUGO_VERSION }}
          extended: true

      - name: Build current
        run: |
          NO_SEARCH=y NO_COMPRESS=y DEST=new/ ./build.sh

      - name: Print filenames changed
        run: diff -qr old/ new/ || true

      - name: Save full diff
        run: diff -r old/ new/ | tee changes.diff || true

      - name: Upload full diff
        uses: actions/upload-artifact@v4
        with:
          name: diff
          path: changes.diff
