name: Deploy Demo

on:
  pull_request_target:
    types: ['opened', 'synchronize']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Start deployment
        uses: bobheadxi/deployments@v0.6.0
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: demo.bbaovanc.com
          ref: ${{ github.event.pull_request.head.sha }}
          no_override: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Build
        run: hugo --i18n-warnings --path-warnings --baseURL "https://demo.bbaovanc.com/pull_request/${{ github.event.number }}"

      - name: Compress
        run: |
          time sudo ./compress.sh

      - name: Upload
        uses: up9cloud/action-rsync@v1
        env:
          HOST: bbaovanc.com
          USER: droneci
          PORT: 2222
          SOURCE: public/
          MODE: push
          VERBOSE: true
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /var/www/demo/pull_request/${{ github.event.number }}/

      - name: Finish deployment
        uses: bobheadxi/deployments@v0.6.0
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: "https://demo.bbaovanc.com/pull_request/${{ github.event.number }}/"

      - name: Find PR comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "preview of this pull request"

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            A preview of this pull request is ready!
            See it at https://demo.bbaovanc.com/pull_request/${{ github.event.number }}/
            View the deploy log at https://github.com/BBaoVanC/bbaovanc.com/actions/runs/${{ github.run_id}}
          edit-mode: replace
